I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


The label new_daytime_2 is defined twice, at File "game/scripts/overview.rpy", line 719:
    call time_event_check from new_daytime_2
and File "game/scripts/overview.rpy", line 730:
    call time_event_check from new_daytime_2


Ren'Py Version: Ren'Py 8.1.3.23091805
Wed Aug 21 19:29:19 2024
