I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


The label say_with_image is defined twice, at File "game/scripts/images.rpy", line 1211:
label say_with_image (image_series, step, text, person_name, person):
and File "game/scripts/overview.rpy", line 617:
label say_with_image (image_series, step, text, person_name, person):


Ren'Py Version: Ren'Py 8.1.3.23091805
Tue Sep 10 19:37:53 2024
