I'm sorry, but an uncaught exception occurred.

While loading the script.
ScriptError: Name ('game/scripts/school.rpy', 1688829332, 2) is defined twice, at game/scripts/school.rpy:222 and game/scripts/school-cdic.rpyc:222.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\RenPy\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "C:\RenPy\renpy\main.py", line 492, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "C:\RenPy\renpy\script.py", line 310, in load_script
    self.load_appropriate_file(".rpyc", [ "_ren.py", ".rpy" ], dir, fn, initcode)
  File "C:\RenPy\renpy\script.py", line 888, in load_appropriate_file
    self.finish_load(stmts, initcode, filename=lastfn) # type: ignore
  File "C:\RenPy\renpy\script.py", line 525, in finish_load
    check_name(node)
  File "C:\RenPy\renpy\script.py", line 501, in check_name
    raise ScriptError("Name %s is defined twice, at %s:%d and %s:%d." %
ScriptError: Name ('game/scripts/school.rpy', 1688829332, 2) is defined twice, at game/scripts/school.rpy:222 and game/scripts/school-cdic.rpyc:222.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.1.23060707
Mind the School dev_0.01
Mon Jul 31 08:10:52 2023
