I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/values.rpy", line 1, in script
    init -98 python:
  File "game/scripts/values.rpy", line 25, in <module>
    get_mod_list()
  File "game/scripts/helper.rpy", line 1013, in get_mod_list
    repair_mod_list()
  File "game/scripts/helper.rpy", line 1045, in repair_mod_list
    if len(persistent.modList.keys()) == 0:
AttributeError: 'NoneType' object has no attribute 'keys'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/values.rpy", line 1, in script
    init -98 python:
  File "D:\RenPy\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\RenPy\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/values.rpy", line 25, in <module>
    get_mod_list()
  File "game/scripts/helper.rpy", line 1013, in get_mod_list
    repair_mod_list()
  File "game/scripts/helper.rpy", line 1045, in repair_mod_list
    if len(persistent.modList.keys()) == 0:
AttributeError: 'NoneType' object has no attribute 'keys'

Windows-10-10.0.22631 
Ren'Py 8.1.3.23091805
Mind the School 0.1.5
Wed Sep  4 17:35:46 2024
